name: Latest Hashnode Blogs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  My-Blogs:
    name: Blogs 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-LIST"
          feed_list: "https://omk.hashnode.dev/feed/omkar"
